plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.141'
    id 'idea'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

sourceSets.main.resources {
    srcDir('src/generated/resources')

    exclude("**/*.bbmodel") // BlockBench project files
    exclude("src/generated/**/.cache") // datagen cache files
}

repositories {
    mavenLocal()
    maven {
        url = "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    maven {
        url = "https://maven.k-4u.nl"
    }
    maven {
        url = "https://maven.latvian.dev/releases"
        content {
            includeGroup "dev.latvian.mods"
            includeGroup "dev.latvian.apps"
        }
    }
    maven {
        url = 'https://jitpack.io'
        content {
            includeGroup "com.github.rtyley"
        }
    }
    maven {
        url = "https://maven.squiddev.cc"
        content {
            includeGroup("cc.tweaked")
        }
    }
    maven {
        url = "https://modmaven.dev/"
    }
}

base {
    archivesName = "NuclearRadiation-${minecraft_version}"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    // accessTransformers = project.files('src/main/resources/META-INF/accesstransformer.cfg')

    runs {
        client {
            client()

            // Comma-separated list of namespaces to load gametests from. Empty = all namespaces.
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
            programArguments.addAll '--width', '1920', '--height', '1080'
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {

    compileOnly("cc.tweaked:cc-tweaked-1.21.1-common-api:1.118.0")
    runtimeOnly("cc.tweaked:cc-tweaked-1.21.1-forge:1.118.0")

    compileOnly "curse.maven:hbms-nuclear-tech-ne-1449927:8062359"

    implementation "curse.maven:curios-309927:6529130"
    compileOnly "curse.maven:curios-309927:6529132"
    compileOnly "curse.maven:nuclear-science-318646:8252492"
    compileOnly "curse.maven:electrodynamics-316867:8252476"
    compileOnly "curse.maven:voltaic-api-1237904:8241610"

    compileOnly "curse.maven:nuclearcraft-neohaul-1523268:8341287"
    compileOnly "curse.maven:terrablender-neoforge-940057:6054947"
    implementation "curse.maven:zerocore-247921:7344742"

    implementation "curse.maven:spark-361579:6225208"
    runtimeOnly "curse.maven:sodium-394468:6382651"
    runtimeOnly "curse.maven:irisshaders-455508:6661598"

    implementation "curse.maven:create-328085:7963363"

    compileOnly "curse.maven:create-nuclear-tech-1533315:8156986"
    compileOnly "curse.maven:create-crowns-968670:8402364"
    compileOnly "curse.maven:chemica-1351412:8188060"
    compileOnly "curse.maven:create-industry-693815:8205648"
    compileOnly "curse.maven:formicapi-1282701:8287469"

    implementation "curse.maven:createnuclear-989797:7329038"

    //implementation "curse.maven:create-creating-space-858897:8348413"

    compileOnly("mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}")
    implementation("mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}")

    compileOnly "curse.maven:emi-580555:8081408"

    compileOnly("mcjty.theoneprobe:theoneprobe:${top_version}:api")
    localRuntime("mcjty.theoneprobe:theoneprobe:${top_version}")
    compileOnly("vazkii.patchouli:Patchouli:${patchouli_version}-NEOFORGE:api")
    runtimeOnly("vazkii.patchouli:Patchouli:${patchouli_version}-NEOFORGE")

    implementation "curse.maven:extreme-reactors-250277:7344744"
    runtimeOnly "curse.maven:multi-builder-tool-827020:8383941"
    implementation("dev.latvian.mods:kubejs-neoforge:${kubejs_version}")
    compileOnly("mekanism:Mekanism:${minecraft_version}-${mekanism_version}:api")
    compileOnly("mekanism:Mekanism:${minecraft_version}-${mekanism_version}")// Mekanism
    compileOnly("mekanism:Mekanism:${minecraft_version}-${mekanism_version}:additions")// Mekanism: Additions
    compileOnly("mekanism:Mekanism:${minecraft_version}-${mekanism_version}:generators")// Mekanism: Generators
    compileOnly("mekanism:Mekanism:${minecraft_version}-${mekanism_version}:tools")// Mekanism: Tools

    compileOnly "curse.maven:applied-energistics-2-223794:7027323"
    implementation "curse.maven:guideme-1173950:7127444"

    testImplementation platform("org.junit:junit-bom:5.10.2")
    testImplementation "org.junit.jupiter:junit-jupiter"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

tasks.named('test', Test) {
    useJUnitPlatform()
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}
sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
